name: digiscan
description: Aplicación predictiva de dígitos.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  share_plus: ^6.3.1

  #Icons
  cupertino_icons: ^1.0.2
  rive: ^0.9.1
  flutter_svg: ^1.1.6

  #Image
  screenshot: ^1.3.0
  file_saver: ^0.1.0
  invert_colors: ^0.0.4
  image: ^3.2.0
  path_provider: ^2.0.12

  #Animate
  animate_do: ^3.0.2

  #Url open
  url_launcher: ^6.1.9

  #Permission 
  permission_handler: ^10.2.0

  #Photograpy
  image_cropper: ^2.0.3
  image_picker: ^0.8.5+3

  #Artificial Intelligence
  flutter_tflite: ^1.0.1
  
  #Splash Screen
  flutter_native_splash: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  #Change app name
  change_app_package_name: ^1.1.0

  #Icon
  flutter_launcher_icons: ^0.11.0

flutter_native_splash:
  color: "#EEF1F8"
  image: assets/images/splash_screen/splash.png
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/images/splash_screen/icon-splash-android12.png

    # Splash screen background color.
    color: "#EEF1F8"

    # App icon background color.
    icon_background_color: "#111111"

    # The branding property allows you to specify an image used as branding in the splash screen.
    #branding: assets/dart.png

    # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
    # apply when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    #image_dark: assets/android12splash-invert.png
    #color_dark: "#042a49"
    #icon_background_color_dark: "#eeeeee"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/icon-white.png"
  min_sdk_android: 21
  adaptive_icon_background: "#EEF1F8"
  adaptive_icon_foreground: "assets/images/icons/icon-white.png"

flutter:
  uses-material-design: true

  assets:
    - assets/artificial_intelligence/
    - assets/icons/
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/icons/
    - assets/images/social_media/
    - assets/rive_assets/
 
  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700

